blank_issues_enabled: false
contact_links:
  - name: '[Let''s Do] Discord Community'
    url: https://discord.gg/let-s-do-collection-1078796799185277079
    about: Just want to hang out or quickly check something? Drop us a message here.
